dist: trusty
sudo: false
language: node_js
node_js: '4'
script:
  - grunt travis:$TEST
cache:
  directories:
    - node_modules
env:
  matrix:
    - TEST=unit-mac-chrome
    - TEST=unit-mac-firefox
    - TEST=unit-mac-safari
    - TEST=unit-windows-chrome
    - TEST=unit-windows-firefox
    - TEST=unit-windows-edge
    - TEST=unit-linux-chrome
    - TEST=unit-linux-firefox
    - TEST=unit-iphone
    - TEST=unit-ipad
    - TEST=unit-android
